# Appendix A - Goodness of Fit Plots {#appendices .appendix-reset}

A goodness of fit plot is produced for each unique analysis run in 2019. All fit plots will contain at least four panels. Each panel is a different depiction of the distribution of the Student Growth Percentiles (SGPs) calculated in that analysis relative to the students' prior or current achievement (i.e. the test scores used as the independent and dependent variables in the model).

The top panel is a mosaic plot that shows the percentage of students that fall into each prior proficiency level, and the location of the `r ord(10)` through `r ord(90)` deciles of the SGP distribution represented as dashed white lines (with the exception of the solid white line for the median/`r ord(50)` percentile). Ideally the median SGP will be at or near 50 for all prior achievement level groups. The top panel is excluded when students' prior achievement level data is unavailable.

The "Ceiling/Floor Effects Test" panel helps identify problems in SGP estimation at the Highest and Lowest Obtainable/Observed Scale Scores (HOSS and LOSS). The table of values shows whether the current year scores at both extremes yield expected SGP values. The expectation is that the majority of SGPs for students scoring at or near the LOSS will be low (preferably less than 5 and not higher than 20), and that SGPs for students scoring at or near the HOSS will be high (preferably higher than 95 and not less than 80). Because few students may score *exactly* at the HOSS/LOSS, the top/bottom 50 students are selected and any student scoring within their range of scores are selected for inclusion in these tables. Consequently, there may be a range of scores at the HOSS/LOSS rather than a single score, and there may be more than 50 students included in the HOSS/LOSS row if the 50 students at the extremes only contain the single HOSS/LOSS score.

The "Student Growth Percentile Range" panel at bottom left shows the empirical distribution of SGPs given prior scale score deciles in the form of a 10 by 10 cell grid. Percentages of student growth percentiles between the `r ord(10)`, `r ord(20)`, `r ord(30)`, `r ord(40)`, `r ord(50)`, `r ord(60)`, `r ord(70)`, `r ord(80)`, and `r ord(90)` percentiles were calculated based upon the empirical decile of the cohort's prior year scaled score distribution^[The total students in each analysis varies depending on grade and subject, and prior score deciles are based only on scores for students used in the SGP calculations.]. Deviations from perfect fit are indicated by red and blue shading. The further above 10 the darker the red, and the further below 10 the darker the blue.

The bottom right panel of each plot is a [Q-Q plot](https://en.wikipedia.org/wiki/Q%E2%80%93Q_plot) which compares the observed distribution of SGPs with the theoretical (uniform) distribution. An ideal plot here will show black step function lines that do not deviate from the ideal, red line which traces the 45 degree angle of perfect fit.

`r if(grepl("SIMEX", params$seq.sgp)) {"Goodness of fit plots for SIMEX measurement error corrected models are presented here for each analysis. The expectations in the SGP distribution panels are different for these models, where lower attaining students will receive higher SGPs and vice versa. This typically shifts the median lines in the mosaic plot panel and causes a red shift (more SGPs than expected) in the upper right and lower left quadrants of the \"Student Growth Percentile Range\" panel."}`

The following sections provide the fit plots for the sequential and skip year analyses. The first section provides the `r skip.excluded.grade` `r if (is.null(params$skip.grades.list)) params$GL_text` plots for the 2019 sequential analyses only. These provide context for what a single prior one-year analysis looks like for `r params$state.name`. The subsequent sections provides the fit plots from both sequential and skip-year analyses for `r capwords(params$GL_text)`. In these `r numbers2words(length(params$GL_subjects))` content area specific sections, the grade level analysis plots are presented with each grade in a row; sequential analyses are in the left column and skip-year analyses are in the right column.
