#' Plot hierarchical shift function
#'
#' Plot hierarchical shift function generated with \code{\link{hsf}}.
#' The function returns a ggplot object, which can be
#' customised using the \href{http://docs.ggplot2.org/current/}{ggplot2}
#' package. Individual shift functions are superimposed in the background. The trimmed mean of the shift functions is plotted on top, with a confidence interval for each quantile.
#' A horizontal line indicates the null reference value entered in \code{hsf}.
#'
#' @references Rousselet, G. A., & Wilcox, R. R. (2019, January 17). Reaction
#'   times and other skewed distributions: problems with the mean and the
#'   median. https://doi.org/10.31234/osf.io/3y54r
#'
#' @param data A list generated by \code{\link{hsf}}.
#' @param viridis_option Viridis colour map for individual shift functions - default = "B".
#' @param ind_line_alpha Alpha transparency for individual shift functions - default = 0.5
#' @param ind_line_size Line thickness for for individual shift functions - default = 0.5
#' @param gp_line_colour Group line colour - default = "black".
#' @param gp_line_size Group line size - default = 1.
#' @param gp_point_colour Group point colour - default = "black".
#' @param gp_point_size Group point size - default = 0.5
#'
#' @return A ggplot object.
#'
#' @examples
#' plot_hsf(out) # default plot
#' p <- plot_hsf(out) # get ggplot object
#' plot_hsf(out, gp_line_colour = "purple", gp_point_colour = "purple") # pink group shift function
#'
#' @export
plot_hsf2 <- function(data,
                      hsf,
                      type="DIFF", # "GES"
                      group_1,
                      group_2 = NULL,
                     viridis_option = "B",
                     ind_line_alpha = 0.5,
                     ind_line_size = 0.5,
                     gp_line_colour = "black",
                     gp_line_size = 1,
                     gp_point_colour = "black",
                     gp_point_size = 0.5
                     ){
  # check input is a list of data frames
  if(!is.list(hsf)){
    stop("hsf must be a list returned by hsf()")
  }
  if(length(hsf)!=8){
    stop("hsf must have length 8, as returned by hsf()")
  }

  group_2 <- list(`Prior Decile` = "PRIOR_DECILE_2YEAR")
  group_1 <- list(Instruction = "INSTRUCTION_MODE")

  data[, participants := factor(seq(nrow(data)))]
  meas.list <- vector(mode = "list", length = 1)
  meas.list[[1]] <- grep(paste0(type, "_"), names(data))
  names(meas.list) <- type

  df <- data.table::melt(data, id = c("participants", group_1[[1]], group_2[[1]]), variable.name = "dec", value.name="diff", measure=grep(paste0(type, "_"), names(data)))
  df[, dec := as.numeric(gsub(paste0(type, "_Q_"), "", dec))/100]
  if (is.list(group_1)) {
    if (is.factor(data[[(group_1[[1]])]]))
      df[, (group_1[[1]]) := factor(get(group_1[[1]]), levels = levels(data[[(group_1[[1]])]]))]
    setnames(df, (group_1[[1]]), names(group_1))
    group_1 <- names(group_1)
  }
  if (is.list(group_2)) {
    if (is.factor(data[[(group_2[[1]])]]))
      df[, (group_2[[1]]) := factor(get(group_2[[1]]), levels = levels(data[[(group_2[[1]])]]))]
    setnames(df, (group_2[[1]]), names(group_2))
    group_2 <- names(group_2)
  }
  setkey(df, participants)

  if (toupper(type)=="DIFF") {
    np <- dim(hsf$individual_sf)[2] # number of participants

    df.gp <- tibble(diff = hsf$group_differences,
                    dec = hsf$quantiles,
                    ymin = hsf$ci[1,],
                    ymax = hsf$ci[2,])
  }

  p <- ggplot(df, aes(x = dec, y = diff)) + #theme_classic() + # theme_dark() + #
       geom_line(alpha = ind_line_alpha, size = ind_line_size,
                 aes(colour = get(group_1), linetype = if(!is.null(group_2)) get(group_2) else NULL,
                     group=participants)) +
       geom_abline(slope = 0, intercept = hsf$null_value)
  if (toupper(type)=="DIFF") p <- p +
       geom_line(data = df.gp, colour = gp_line_colour, size = gp_line_size)
  if (toupper(type)=="DIFF") p <- p +
       geom_pointrange(data = df.gp, aes(ymin = ymin, ymax = ymax), colour = gp_point_colour, size = gp_point_size)
  p <- p + scale_colour_viridis_d(option = "C") + # viridis_option
    # scale_color_brewer(palette = "Dark2") +
    scale_x_continuous(breaks = hsf$quantiles) +
    theme(#legend.position = "none",
          panel.background = element_rect(colour="#515151", fill="#515151"),
          panel.border = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          plot.title = element_text(size = 22),
          axis.title.x = element_text(size = 18),
          axis.text = element_text(size = 16, colour = "black"),
          axis.title.y = element_text(size = 18)) +
    labs(x = "Quantiles", y = "Differences") +
    # ggtitle(paste0(hsf$comparison," quantile differences"))
    ggtitle(hsf$comparison)

  suppressMessages(p)
}
